export enum StageEnum {
    APPLIED = "APPLIED",
    PHONE_SCREEN = "PHONE_SCREEN",
    SCREENING = "SCREENING",
    TECHNICAL_INTERVIEW = "TECHNICAL_INTERVIEW",
    FINAL_INTERVIEW = "FINAL_INTERVIEW",
    OFFER = "OFFER",
    REJECTED = "REJECTED"
}